export default ScreenType = {
    /**
     * Cannot create value = -1 here
     */
    FROM_USER_PROFILE: 1,
    FROM_LOGIN: 2,
    FROM_FORGET_PASSWORD: 3,
    FROM_ORDER_HISTORY: 4,
    FROM_LOGIN_SOCIAL: 5,
    FROM_REGISTER: 6,
    FROM_HOME_VIEW: 7,
    FROM_TIMEKEEPING_HISTORY: 8,
    FROM_TIMEKEEPING_HISTORY_DETAIL: 9,
    FROM_SALARY_HISTORY: 10,
    FROM_SPLASH: 11,
    FROM_STAFF_SALARY: 12,
    FROM_STAFF_DEPARTMENT: 13,
    FROM_COMPANY_LIST: 14,
    FROM_SLIDING_MENU: 15,
    FROM_CHAT_EDIT: 16,
    FROM_CHAT_INVITE: 17,
    FROM_CREATE_CHAT_GROUP: 18,
    FROM_CREATE_CHAT: 19
}