import { combineEpics } from "redux-observable";
import {
  loginEpic,
  registerEpic,
  getUserInfoEpic,
  editProfileEpic,
  changePassEpic,
  signUp,
  forgetPassEpic,
  getReviewEpic,
  postReviewEpic,
  getNotificationsEpic,
  getNotificationsViewEpic,
  loginGoogleEpic,
  loginFacebookEpic,
  getConfigEpic,
  sendOTPEpic,
  confirmOTPEpic,
  postUserDeviceInfoEpic,
  deleteUserDeviceInfoEpic,
  countNewNotificationEpic,
  searchNotificationEpic,
  readAllNotificationEpic,
  getNotificationsByTypeEpic,
  saveAddressEpic,
  searchAddressEpic,
  getMemberOfConversationEpic,
  editChatGroupEpic,
  createConversationEpic,
  getProfileAdminEpic,
  getListPartnerEpic,
  savePartnerEpic,
  deleteConversationEpic,
  searchConversationEpic,
  checkExistConversationEpic,
  checkExistConversationInHomeEpic,
  checkConversationActiveEpic,
  getProfileUserChatEpic,
  getFriendsChatViewEpic,
  getMemberGroupChatViewEpic,
  getSchoolsEpic,
  getFeedbackMedicalExaminationEpic,
  getFirebaseTokenEpic,
  getCompanyDetailEpic,
  getListDepartmentEpic,
  updateDepartmentEpic,
  getCompaniesEpic,
  getBranchesEpic,
  deniedStaffEpic,
  getListConversationEpic,
  configStaffEpic
} from "./userEpics";
import {
  getSalaryEpic,
  getDetailTypeSalaryEpic,
  getStaffSalaryEpic,
  getSalaryConfigEpic
} from "./salaryEpic";
import {
  getUpdateVersionEpic,
  getAreaEpic,
  saveExceptionEpic,
  getProvinceHCMEpic,
  getTimeTodayEpic
} from "./commonEpic";
import { from } from "rxjs";
import { getBannerEpic } from "./bannerEpic";
import {
  getBranchEpic,
  searchBranchEpic,
  getMyLocationEpic
} from "./locationEpic";
import {
  getWiFiConfigEpic,
  getWiFiConfigAdminEpic,
  getWorkingTimeConfigEpic,
  getWorkingTimeConfigByUserIdEpic,
  timekeepingEpic,
  getTimekeepingEpic,
  getTimekeepingHistoryEpic,
  getTimekeepingHistoryDetailEpic,
  getTimekeepingListEpic,
  approvalTimekeepingEpic,
  timekeepingAdminEpic,
  timekeepingUpdateEpic,
  timekeepingDeleteEpic
} from "./timekeepingEpic";
import {
  getSabbaticalsEpic,
  registerSabbaticalEpic,
  updateSabbaticalEpic,
  deleteSabbaticalEpic,
  getSabbaticalsAdminEpic,
  approvedSabbaticalEpic,
  deniedSabbaticalEpic
} from "./sabbaticalEpic";
import {
  getDashboardStatisticalEpic,
  getListStaffDepartmentEpic
} from "./companyEpic";
import {
  createGroupFaceRecognizeEpic,
  getGroupFaceRecognizeEpic,
  trainingPersonGroupEpic,
  deletePersonGroupPersonEpic
} from "./faceEpic";
import {
  getGifTrendingEpic,
  searchGifEpic
} from "./tenorEpic";
import {
  getTaskEpic,
  getTaskDetailEpic,
  updateTaskEpic,
  updateTaskDetailEpic,
  getTaskTimeConfigEpic
} from './taskEpic';

export default combineEpics(
  loginEpic,
  loginGoogleEpic,
  loginFacebookEpic,
  registerEpic,
  changePassEpic,
  getUserInfoEpic,
  editProfileEpic,
  signUp,
  forgetPassEpic,
  getReviewEpic,
  postReviewEpic,
  getNotificationsEpic,
  getNotificationsViewEpic,
  getConfigEpic,
  getUpdateVersionEpic,
  sendOTPEpic,
  confirmOTPEpic,
  postUserDeviceInfoEpic,
  deleteUserDeviceInfoEpic,
  countNewNotificationEpic,
  getBannerEpic,
  getBranchEpic,
  searchNotificationEpic,
  readAllNotificationEpic,
  getNotificationsByTypeEpic,
  saveAddressEpic,
  searchAddressEpic,
  getAreaEpic,
  getMemberOfConversationEpic,
  editChatGroupEpic,
  createConversationEpic,
  getProfileAdminEpic,
  getListPartnerEpic,
  savePartnerEpic,
  deleteConversationEpic,
  searchConversationEpic,
  checkExistConversationEpic,
  checkExistConversationInHomeEpic,
  saveExceptionEpic,
  checkConversationActiveEpic,
  getSchoolsEpic,
  searchBranchEpic,
  getProvinceHCMEpic,
  getFeedbackMedicalExaminationEpic,
  getFirebaseTokenEpic,
  getSalaryEpic,
  getStaffSalaryEpic,
  getDetailTypeSalaryEpic,
  getMyLocationEpic,
  getWiFiConfigEpic,
  getWiFiConfigAdminEpic,
  timekeepingEpic,
  getWorkingTimeConfigEpic,
  getWorkingTimeConfigByUserIdEpic,
  getTimekeepingEpic,
  getTimekeepingHistoryEpic,
  getTimekeepingHistoryDetailEpic,
  getTimeTodayEpic,
  getCompanyDetailEpic,
  getSabbaticalsEpic,
  registerSabbaticalEpic,
  updateSabbaticalEpic,
  deleteSabbaticalEpic,
  getListDepartmentEpic,
  updateDepartmentEpic,
  getListConversationEpic,
  getFriendsChatViewEpic,
  getMemberGroupChatViewEpic,
  getCompaniesEpic,
  getBranchesEpic,
  getDashboardStatisticalEpic,
  getTimekeepingListEpic,
  getSabbaticalsAdminEpic,
  approvedSabbaticalEpic,
  deniedSabbaticalEpic,
  getListStaffDepartmentEpic,
  approvalTimekeepingEpic,
  deniedStaffEpic,
  configStaffEpic,
  getSalaryConfigEpic,
  createGroupFaceRecognizeEpic,
  getGroupFaceRecognizeEpic,
  trainingPersonGroupEpic,
  deletePersonGroupPersonEpic,
  getGifTrendingEpic,
  searchGifEpic,
  timekeepingAdminEpic,
  timekeepingUpdateEpic,
  timekeepingDeleteEpic,
  getTaskEpic,
  getTaskDetailEpic,
  updateTaskEpic,
  updateTaskDetailEpic,
  getTaskTimeConfigEpic
);
